// Live chat widget embedded just below the "LIVE FROM THE LAB" token counter.
// Talks to the self-hosted AgentGateway's OpenAI-compatible endpoint using its
// "default" virtual model, which routes to whatever model is currently loaded
// in LM Studio. The model is seeded with a system prompt containing the full
// content of this site so it can answer questions about Spencer and knows
// exactly where its own interface lives.

const LAB_CHAT_API_URL = "https://llm.spencerheywood.com/v1/chat/completions";
const LAB_CHAT_MCP_URL = "https://mcp.spencerheywood.com/mcp/";
const LAB_CHAT_MODEL = "default";
const LAB_CHAT_API_KEY = "sk-H0N--ManXvqqDGza-pA8dA";
const LAB_CHAT_EMAIL_RECIPIENT = "contact@spencerheywood.com";
const LAB_CHAT_EMAIL_TOOL = "general_send_email";
const LAB_CHAT_TOOLS = [{
    type: "function",
    function: {
        name: "send_email",
        description: "Send one email directly to Spencer at his fixed contact address. Use only when the visitor explicitly asks to send or email a message to Spencer.",
        parameters: {
            type: "object",
            properties: {
                subject: { type: "string", description: "A concise subject line." },
                body: { type: "string", description: "The complete plain-text email message." }
            },
            required: ["subject", "body"],
            additionalProperties: false
        }
    }
}];

// Hidden context: everything on the site, so answers stay accurate without
// the model needing access to the page itself. Kept in sync with index.html —
// if a section changes there, update this too.
const LAB_CHAT_SYSTEM_PROMPT = `You are "Lab Chat," a friendly AI assistant embedded in Spencer Heywood's personal website, spencerheywood.com.

Where you live: your interface is a small live-chat widget on the home page, located directly below the "LIVE FROM THE LAB" card. That card shows a running counter of tokens generated by models running on Spencer's own local hardware, served through his self-hosted AgentGateway at llm.spencerheywood.com — and you are one of those local models: served by LM Studio and exposed through that same gateway under its "default" virtual model, so the underlying model is whichever one is currently loaded (right now, Qwen 3.8 27B). If anyone asks what you are or where you're running, explain this accurately in a sentence or two.

Keep your internal reasoning short so visitors get answers quickly. How to behave: be conversational, warm, and concise — most answers should be 2-6 sentences. Ground every factual claim about Spencer, his work, or his hardware in the site context below; never invent jobs, projects, numbers, or specs. If asked for something not covered by this context (or personal advice beyond the site), say you don't have that information and suggest emailing Spencer at contact@spencerheywood.com. You may reference page sections by name ("AI Systems Lab," "Selected Projects") so people can find the details on the page itself.

You can send one plain-text email directly to Spencer when a visitor explicitly asks you to send or email him a message. Use the send_email tool in that case, choosing a concise subject and preserving the visitor's intended message. Never claim an email was sent unless the tool reports success, and never make more than one tool call for a visitor message. The recipient is fixed and cannot be changed.

SITE CONTEXT
- Identity & positioning: Spencer Heywood, Software Systems Engineer — practical AI and industrial automation. Headline: "From AI opportunity to measurable business value." He translates operational needs into practical AI and automation: use-case evaluation, architecture, implementation, rollout, and production support. Current focus areas: use-case discovery; business impact & feasibility; AI solution architecture; hands-on implementation; adoption & enablement; production integration.
- Current role — BEUMER Group (2+ years), Software Systems Engineer II: high-throughput intralogistics systems, enterprise AI, systems integration. He engineers and validates systems across software, databases, networks, host integrations, and industrial controls; 3,000+ items per minute throughput; production troubleshooting; AI architecture & evaluation.
- Delaire USA (2+ years, part-time), Software & Systems Engineer: modernizing enterprise infrastructure, security, monitoring, and software while evaluating LLM and RAG use cases.
- SERVO / BookServo.com (~3.5 years as founder/founding developer, 2021–2024): a services marketplace he built and operated from concept through production — integrating 10+ partner companies with scheduling (Google Calendar API), payments (Stripe), and operational workflows; end-to-end product & architecture ownership; technical cost per session down 91%+. Stack: Ruby on Rails, PostgreSQL, AWS.
- End-to-end delivery process (the "End-to-End Delivery" section): (01) Identify & prioritize — structure opportunities around business impact, feasibility, risk, and operational fit; (02) Build the solution — automation, data pipelines, AI applications, integrations, governed access; (03) Deploy & enable — production integration, team education, documentation, adoption; (04) Measure & improve — evaluate quality, reliability, utilization, and value.
- AI Systems Lab: a home hardware lab that grew out of a hobby build. V1 was an air-cooled desktop with an RTX 5060 Ti (16 GB VRAM, up to 180 W) for first local benchmarks; V2 upgraded to an RTX PRO 4500 (24 GB, ~200 W) for larger models and sustained workloads; V3 — the current workstation — is a water-cooled build around an RTX PRO 6000 (96 GB VRAM, up to 600 W), designed as one system for power, thermals, airflow, and reliability, putting out 5M+ tokens per week locally. Supporting infrastructure: a Tesla P40 installed in a repurposed Dell PowerEdge R520 rack server, and an always-on Dell OptiPlex 5070 home server that hosts his websites, the LLM/MCP gateway, NAS, and VPN (150+ days uptime). The lab is social too — LAN parties and shared build sessions keep it hands-on and fun.
- Selected projects: the featured one is SERVO/BookServo.com; earlier work includes DashDoor, Nugget Rush, Home Keeper, HowToBuildYourOwnHome.com, and SmileWizard.com (all linked in "Selected Projects").
- Technical capabilities: AI & agents — LLMs, RAG, MCP, AgentGateway, LM Studio, OpenAI-compatible APIs, agent tooling, model evaluation; languages — Python, C#, C++, Ruby, JavaScript, TypeScript; frameworks — Ruby on Rails, Angular, React, Node.js; data — Microsoft SQL Server, PostgreSQL, Elasticsearch/Kibana; infrastructure — Linux, Windows Server, Nginx, AWS, networking; engineering & automation — distributed systems, system integration, troubleshooting, validation & testing, Power Automate, Office Scripts.
- Education: App Academy (Full-Stack Software Engineering).
- Contact details (share only if asked): email contact@spencerheywood.com, phone (971) 777-1485, LinkedIn linkedin.com/in/spencer-heywood, GitHub github.com/heyspence; his resume is available as a Google Docs link in the page header.`;

// Keep four complete user/assistant turns so the local model stays responsive.
const LAB_CHAT_MAX_TURNS = 4;
const LAB_CHAT_REQUEST_TIMEOUT_MS = 60000;
// How long to wait before retrying a request the gateway rejected as busy.
const LAB_CHAT_BUSY_RETRY_DELAY_MS = 2000;

(function initLabChat() {
    const toggleEl = document.getElementById("lab-chat-toggle");
    if (!toggleEl) return;

    const bodyEl = document.getElementById("lab-chat-body");
    const logEl = document.getElementById("lab-chat-log");
    const formEl = document.getElementById("lab-chat-form");
    const inputEl = document.getElementById("lab-chat-input");
    const sendEl = formEl.querySelector(".lab-chat-send");
    const starterEls = Array.from(document.querySelectorAll(".lab-chat-starters [data-prompt]"));
    const usageEl = document.getElementById("lab-chat-usage");

    const history = [];

    function addMessage(role, text, isTyping = false) {
        const li = document.createElement("li");
        li.className = "lab-msg" + (role === "user" ? " lab-msg-user" : "");

        const tag = document.createElement("span");
        tag.className = "lab-msg-tag";
        tag.textContent = role === "user" ? "YOU" : "LOCAL MODEL";

        let bubble;
        if (isTyping) {
            bubble = document.createElement("div");
            bubble.className = "lab-chat-typing";
            bubble.setAttribute("role", "status");
            bubble.setAttribute("aria-label", "The local model is generating a response");

            for (let index = 0; index < 3; index += 1) {
                const dot = document.createElement("span");
                dot.setAttribute("aria-hidden", "true");
                bubble.appendChild(dot);
            }
        } else {
            const message = String(text || "");
            if (message.startsWith("[error]")) li.classList.add("lab-msg-error");
            bubble = document.createElement("div");
            bubble.className = "lab-msg-bubble";
            bubble.textContent = message.replace(/^\[error\]\s*/, "");
        }

        li.append(tag, bubble);
        logEl.appendChild(li);
        logEl.scrollTop = logEl.scrollHeight;
        return { li, bubble };
    }

    function setUsageStatus(message) {
        if (!usageEl) return;
        usageEl.textContent = message;
        usageEl.hidden = !message;
    }

    function addToolStatus(message) {
        const status = addMessage("tool", message);
        status.li.classList.add("lab-msg-tool");
        status.li.querySelector(".lab-msg-tag").textContent = "ACTION";
        return status;
    }

    function parseMcpResponse(text) {
        const dataLines = text.split(/\r?\n/)
            .filter((line) => line.startsWith("data:"))
            .map((line) => line.slice(5).trim());
        const payload = dataLines.length > 0 ? dataLines.join("\n") : text.trim();
        if (!payload) throw new Error("Empty tool response");
        return JSON.parse(payload);
    }

    async function mcpPost(payload, sessionId, signal) {
        const headers = {
            "Content-Type": "application/json",
            Accept: "application/json, text/event-stream",
            Authorization: "Bearer " + LAB_CHAT_API_KEY
        };
        if (sessionId) headers["Mcp-Session-Id"] = sessionId;

        return fetch(LAB_CHAT_MCP_URL, {
            method: "POST",
            headers,
            signal,
            body: JSON.stringify(payload)
        });
    }

    // The agentgateway MCP endpoint speaks Streamable HTTP and requires a
    // session before tools/call: initialize (returns mcp-session-id), then the
    // notifications/initialized notification, then the tool call.
    async function openMcpSession(signal) {
        const initResponse = await mcpPost({
            jsonrpc: "2.0",
            id: 1,
            method: "initialize",
            params: {
                protocolVersion: "2025-06-18",
                capabilities: {},
                clientInfo: { name: "spencerheywood-lab-chat", version: "1.0" }
            }
        }, null, signal);

        if (!initResponse.ok) throw new Error(`MCP initialize HTTP ${initResponse.status}`);
        await initResponse.text();
        const sessionId = initResponse.headers.get("mcp-session-id");
        if (!sessionId) throw new Error("Missing MCP session ID from gateway");

        const notifyResponse = await mcpPost(
            { jsonrpc: "2.0", method: "notifications/initialized" },
            sessionId,
            signal
        );
        if (!notifyResponse.ok) throw new Error(`MCP initialized HTTP ${notifyResponse.status}`);

        return sessionId;
    }

    async function sendEmail(subject, body, signal) {
        const cleanSubject = String(subject || "").trim().slice(0, 200);
        const cleanBody = String(body || "").trim().slice(0, 5000);
        if (!cleanSubject || !cleanBody) throw new Error("Email subject and body are required");

        const sessionId = await openMcpSession(signal);

        const response = await mcpPost({
            jsonrpc: "2.0",
            id: 2,
            method: "tools/call",
            params: {
                name: LAB_CHAT_EMAIL_TOOL,
                arguments: {
                    to: LAB_CHAT_EMAIL_RECIPIENT,
                    subject: cleanSubject,
                    body: cleanBody
                }
            }
        }, sessionId, signal);

        if (!response.ok) throw new Error(`Tool HTTP ${response.status}`);
        const payload = parseMcpResponse(await response.text());
        if (payload.error || !payload.result || payload.result.isError) {
            throw new Error("Email tool reported an error");
        }

        return "Email sent successfully to Spencer.";
    }

    async function requestCompletion(messages, signal, toolChoice = "auto") {
        const payload = JSON.stringify({
            model: LAB_CHAT_MODEL,
            messages,
            tools: LAB_CHAT_TOOLS,
            tool_choice: toolChoice,
            parallel_tool_calls: false,
            temperature: 0.4,
            max_tokens: 1024
        });

        for (let attempt = 0; ; attempt++) {
            const response = await fetch(LAB_CHAT_API_URL, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: "Bearer " + LAB_CHAT_API_KEY
                },
                signal,
                body: payload
            });

            if (response.ok) {
                return response.json();
            }

            // The local GPU is busy — the gateway can route a failed request to an
            // API provider, so retry once before surfacing the error.
            if (response.status === 429 && attempt === 0) {
                await new Promise((resolve) => window.setTimeout(resolve, LAB_CHAT_BUSY_RETRY_DELAY_MS));
                continue;
            }

            const error = new Error(`HTTP ${response.status}`);
            error.status = response.status;
            throw error;
        }
    }

    function setBusy(busy) {
        sendEl.disabled = busy;
        inputEl.readOnly = busy;
        bodyEl.classList.toggle("is-busy", busy);
        logEl.setAttribute("aria-busy", String(busy));
        starterEls.forEach((button) => {
            button.disabled = busy;
        });
    }

    function openChat(focus = true) {
        bodyEl.hidden = false;
        toggleEl.setAttribute("aria-expanded", "true");

        if (logEl.children.length === 0) {
            addMessage(
                "assistant",
                "Hi — I'm running on Spencer's local workstation. Ask about his experience, projects, or AI lab, or ask me to email him a message; each answer will show up in the token counter above."
            );
        }

        if (focus) {
            window.requestAnimationFrame(() => inputEl.focus());
        }
    }

    function closeChat() {
        bodyEl.hidden = true;
        toggleEl.setAttribute("aria-expanded", "false");
    }

    function responseErrorMessage(error) {
        if (error.name === "AbortError") {
            return "The local model took too long to respond. Your question is ready to retry.";
        }
        if (error.status === 429) {
            return "The local GPU is busy with another request. Give it a moment and try again.";
        }
        if (error.status === 502 || error.status === 503) {
            return "The lab is temporarily unavailable. Your question is ready to retry.";
        }
        if (error.isEmailError) {
            return "The email couldn't be sent. Your message is ready to retry.";
        }
        return "The chat request didn't complete. Your question is ready to retry.";
    }

    toggleEl.addEventListener("click", () => {
        if (bodyEl.hidden) {
            openChat();
        } else {
            closeChat();
        }
    });

    starterEls.forEach((button) => {
        button.addEventListener("click", () => {
            if (sendEl.disabled) return;
            inputEl.value = button.dataset.prompt || button.textContent.trim();
            formEl.requestSubmit();
        });
    });

    document.addEventListener("lab-telemetry-synced", (event) => {
        const expectedUsage = Number(event.detail && event.detail.expectedUsage) || 0;
        const answerCopy = expectedUsage > 0
            ? `This answer processed ${expectedUsage.toLocaleString("en-US")} tokens locally.`
            : "This answer was generated locally.";
        setUsageStatus(`${answerCopy} Lifetime counter refreshed.`);
    });

    document.addEventListener("lab-telemetry-sync-timeout", (event) => {
        const expectedUsage = Number(event.detail && event.detail.expectedUsage) || 0;
        const answerCopy = expectedUsage > 0
            ? `This answer processed ${expectedUsage.toLocaleString("en-US")} tokens locally.`
            : "This answer was generated locally.";
        setUsageStatus(`${answerCopy} The lifetime counter will catch up on the next gateway refresh.`);
    });

    formEl.addEventListener("submit", async (event) => {
        event.preventDefault();
        const text = inputEl.value.trim();
        if (!text || sendEl.disabled) return;

        const userMessage = { role: "user", content: text };
        addMessage("user", text);
        inputEl.value = "";
        inputEl.focus();
        setBusy(true);
        setUsageStatus("Generating on Spencer's local GPU…");
        const typing = addMessage("assistant", "", true);
        document.dispatchEvent(new CustomEvent("lab-chat-start"));

        const controller = new AbortController();
        const timeout = window.setTimeout(() => controller.abort(), LAB_CHAT_REQUEST_TIMEOUT_MS);

        try {
            const messages = [
                { role: "system", content: LAB_CHAT_SYSTEM_PROMPT },
                ...history.slice(-(LAB_CHAT_MAX_TURNS * 2)),
                userMessage
            ];

            let data = await requestCompletion(messages, controller.signal);
            let responseMessage = data.choices && data.choices[0] && data.choices[0].message;
            let totalTokens = Math.max(0, Number(data.usage && data.usage.total_tokens) || 0);
            const toolCall = responseMessage && Array.isArray(responseMessage.tool_calls)
                ? responseMessage.tool_calls.find((call) => call.function && call.function.name === "send_email")
                : null;

            if (toolCall) {
                const toolStatus = addToolStatus("Sending email to Spencer…");
                let toolResult;

                try {
                    const emailArguments = JSON.parse(toolCall.function.arguments || "{}");
                    toolResult = await sendEmail(emailArguments.subject, emailArguments.body, controller.signal);
                    toolStatus.bubble.textContent = "Email sent to Spencer.";
                    toolStatus.li.classList.add("is-complete");
                } catch (emailError) {
                    toolStatus.bubble.textContent = "Email could not be sent.";
                    toolStatus.li.classList.add("is-error");
                    emailError.isEmailError = true;
                    throw emailError;
                }

                data = await requestCompletion([
                    ...messages,
                    {
                        role: "assistant",
                        content: responseMessage.content || "",
                        tool_calls: [toolCall]
                    },
                    {
                        role: "tool",
                        tool_call_id: toolCall.id,
                        content: toolResult
                    }
                ], controller.signal, "none");
                responseMessage = data.choices && data.choices[0] && data.choices[0].message;
                totalTokens += Math.max(0, Number(data.usage && data.usage.total_tokens) || 0);
            }

            const reply = responseMessage ? String(responseMessage.content || "").trim() : "";
            if (!reply) throw new Error("Empty model response");
            history.push(userMessage, { role: "assistant", content: reply });
            while (history.length > LAB_CHAT_MAX_TURNS * 2) history.splice(0, 2);

            if (typing.li.isConnected) typing.li.remove();
            addMessage("assistant", reply);
            setUsageStatus(totalTokens > 0
                ? `This answer processed ${totalTokens.toLocaleString("en-US")} tokens locally · syncing the lifetime counter…`
                : "Answer generated locally · syncing the lifetime counter…");

            document.dispatchEvent(new CustomEvent("lab-chat-complete", {
                detail: { totalTokens }
            }));
        } catch (error) {
            console.warn("[lab-chat] request failed:", error.message);
            if (typing.li.isConnected) typing.li.remove();
            addMessage("assistant", `[error] ${responseErrorMessage(error)}`);
            if (!inputEl.value.trim()) inputEl.value = text;
            setUsageStatus("");
            document.dispatchEvent(new CustomEvent("lab-chat-error"));
        } finally {
            window.clearTimeout(timeout);
            setBusy(false);
            logEl.scrollTop = logEl.scrollHeight;
        }
    });

    // Keep the chat expanded by default; skip auto-focus so mobile
    // keyboards don't open before a visitor chooses to type.
    openChat(false);
})();
